//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodaiBot.Common.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alias> Alias { get; set; }
        public virtual DbSet<Guild> Guild { get; set; }
        public virtual DbSet<GuildAlias> GuildAlias { get; set; }
        public virtual DbSet<GuildUser> GuildUser { get; set; }
        public virtual DbSet<GuildUserSnapshot> GuildUserSnapshot { get; set; }
        public virtual DbSet<Snapshot> Snapshot { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAlias> UserAlias { get; set; }
    }
}
