//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodaiBot.Common.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuildUserSnapshot
    {
        public System.Guid Id { get; set; }
        public System.Guid GuildUserId { get; set; }
        public System.Guid SnapshotId { get; set; }
    
        public virtual GuildUser GuildUser { get; set; }
        public virtual Snapshot Snapshot { get; set; }
    }
}
