//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodaiBot.Common.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snapshot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Snapshot()
        {
            this.GuildUserSnapshot = new HashSet<GuildUserSnapshot>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuildUserSnapshot> GuildUserSnapshot { get; set; }
    }
}
